name: SAST Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sast:
    uses: JasmineH-H/SAST-Pentest-Tool/.github/workflows/sast.yml@main
    with:
      backend_api_url: ${{ vars.BACKEND_API_URL }}
    secrets:
      INGEST_TOKEN: ${{ secrets.INGEST_TOKEN_SAST
      
       }}